# Generated by Django 5.2.8 on 2025-12-04 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dental_appointments", "0002_dentalappointmentstatus_and_more"),
        ("dental_records", "0003_dentist_dentist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentalappointment",
            name="appointment_status",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="appointment_status",
                to="dental_appointments.dentalappointmentstatus",
            ),
        ),
        migrations.AlterField(
            model_name="dentalappointment",
            name="dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="dental_records.dentist",
            ),
        ),
    ]
