# Generated by Django 5.2.8 on 2025-12-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keycloak_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keycloakuser",
            name="roles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
