# Generated by Django 5.2.8 on 2025-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dental_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_image",
            field=models.ImageField(blank=True, null=True, upload_to="patient_images/"),
        ),
    ]
