# Generated by Django 5.2.8 on 2025-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dental_records", "0002_patient_patient_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="dentist_image",
            field=models.ImageField(blank=True, null=True, upload_to="dentist_images/"),
        ),
    ]
